In [2]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
df = pd.read_csv(prefix + 'yellow_tripdata_2021-01.csv.gz', nrows=100)

In [3]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [4]:
df.dtypes

VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count            int64
trip_distance            float64
RatecodeID                 int64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [5]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

In [6]:
df.dtypes

VendorID                          Int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   Int64
trip_distance                   float64
RatecodeID                        Int64
store_and_fwd_flag       string[python]
PULocationID                      Int64
DOLocationID                      Int64
payment_type                      Int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
dtype: object

In [7]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [8]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [9]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [14]:
from tqdm.auto import tqdm
first = True

df_iter = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

for df_chunk in tqdm(df_iter):

    if first:
        # Create table schema (no data)
        df_chunk.head(0).to_sql(
            name="yellow_taxi_data",
            con=engine,
            if_exists="replace"
        )
        first = False
        print("Table created")

    # Insert chunk
    df_chunk.to_sql(
        name="yellow_taxi_data",
        con=engine,
        if_exists="append"
    )

    print("Inserted:", len(df_chunk))

0it [00:00, ?it/s]

Table created
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 100000
Inserted: 69765

----

In [9]:
z_prefix = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/"
df_iter = pd.read_csv(z_prefix+
    'taxi_zone_lookup.csv',
    iterator=True,
    chunksize=100000,
)

In [11]:
df = next(df_iter)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    object
 2   Zone          264 non-null    object
 3   service_zone  263 non-null    object
dtypes: int64(1), object(3)
memory usage: 8.4+ KB

----

In [27]:
prefix = "https://d37ci6vzurychx.cloudfront.net/trip-data/"  #"/Users/hemavakade/Documents/zoomcamp/DataEngineering/data-engineering-zoomcamp/data/ny_taxi_postgres_data/"
file = prefix + "green_tripdata_2025-11.parquet"
df_green = pd.read_parquet(file)

In [30]:
len(df_green)

46912

In [23]:
zones = prefix + "taxi_zone_lookup.csv"
df_zones = pd.read_csv(zones, dtype={"Borough":"string", "Zone":"string", "service_zone":"string" })

In [24]:
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [25]:
df_green.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46912 entries, 0 to 46911
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               46912 non-null  int32
 1   lpep_pickup_datetime   46912 non-null  datetime64[us]
 2   lpep_dropoff_datetime  46912 non-null  datetime64[us]
 3   store_and_fwd_flag     41343 non-null  object
 4   RatecodeID             41343 non-null  float64
 5   PULocationID           46912 non-null  int32
 6   DOLocationID           46912 non-null  int32
 7   passenger_count        41343 non-null  float64
 8   trip_distance          46912 non-null  float64
 9   fare_amount            46912 non-null  float64
 10  extra                  46912 non-null  float64
 11  mta_tax                46912 non-null  float64
 12  tip_amount             46912 non-null  float64
 13  tolls_amount           46912 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  46912 non-null  float64
 16  total_amount           46912 non-null  float64
 17  payment_type           41343 non-null  float64
 18  trip_type              41342 non-null  float64
 19  congestion_surcharge   41343 non-null  float64
 20  cbd_congestion_fee     46912 non-null  float64
dtypes: datetime64[us](2), float64(15), int32(3), object(1)
memory usage: 7.0+ MB

In [26]:
df_zones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    string
 2   Zone          264 non-null    string
 3   service_zone  263 non-null    string
dtypes: int64(1), string(3)
memory usage: 8.4 KB

----

**Q3**

```sql
SELECT
	COUNT(1)
FROM
	GREEN_TAXI_TRIPS
WHERE
	TRIP_DISTANCE <= 1
	AND DATE (LPEP_PICKUP_DATETIME) >= '2025-11-01' 
	and DATE (LPEP_PICKUP_DATETIME) < '2025-12-01'
```

**Q4**
``` sql

select max(td), dt from (
select sum(trip_distance) td, date(lpep_pickup_datetime) dt from GREEN_TAXI_TRIPS 
where trip_distance < 100.00
group by date(lpep_pickup_datetime) ORDER BY 1) as tab group by dt order by 1 desc

```

**Q5**


```sql

SELECT
	MAX(TOT_AMT),
	ZNS."Zone"
FROM
	(
		SELECT
			SUM(TOTAL_AMOUNT) TOT_AMT,
			G."PULocationID" LOC_ID
		FROM
			GREEN_TAXI_TRIPS G
		WHERE
			DATE (LPEP_PICKUP_DATETIME) = '2025-11-18'
		GROUP BY
			2
	) AS TAB
	JOIN ZONES ZNS ON TAB.LOC_ID = ZNS."LocationID"
GROUP BY
	2
ORDER BY
	1 DESC
limit 1
```

**Q6**

```sql



SELECT
	max(tip_amount), du_ZNS."Zone"
FROM
	GREEN_TAXI_TRIPS G
	JOIN ZONES pu_ZNS ON g."PULocationID" = pu_ZNS."LocationID"
	join ZONES du_ZNS ON g."DOLocationID" = du_ZNS."LocationID"
where pu_ZNS."Zone"  = 'East Harlem North'
group by 2
order by 1 desc
limit 1
```